# Jekyll AO Paper
#
# This is the configuration file

title: American Oneironautics
email: americanoneironautics@gmail.com
name: American Oneironautics
description: >- # this means to ignore newlines until "baseurl:"
  Wait just a metaphysical moment...
keywords: [American][Oneironautics][literature][dreams]
baseurl: '' # the subpath, e.g. /`blog
url: '' # the base hostname & protocol, e.g. http://example.com
domain: 'americanoneironautics.com' # the domain name, e.g. example.com
language: en
# Supported languages list:
# en: English
# de: Deutsche (German)
# es: Español (Spanish)
# fr: Français (French)
# ja: 日本語 (Japanese)
# pt: Português (Portuguese)
# zh-cn: 简体中文 (Simplified Chinese)
# zh-tw: 繁體中文 (Traditional Chinese)

analytics: # the Google Analytics property ID, e.g. UA-XXXXX-Y

comments: false # enable comments
disqus: # disqus account

mathjax: true # Math support
diagram: true # Diagrams support

paginate: 25
paginate_path: '/page:num/'

permalink: /:year/:month/:day/:title

sass:
  sass_dir: _sass
  style: expanded # compressed, compact, expanded or compressed

# Build settings
markdown: kramdown
plugins:
  - github-pages
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
